import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';

const BlogDynamic = () => {
     
    const router = useRouter();
     const {blogId} = router.query

     console.log(blogId)
    return (
        <div>
             <Head>
                <title>Dynamic Blog Pages </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <p>This is the blog {blogId}</p>
        </div>
    );
};

export default BlogDynamic;