import Head from 'next/head'
import Image from 'next/image'
import Hakkani from '../Components/Hakkani'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next js Basic To Advanced</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* show the personal details  */}

      <Hakkani name="Golam Hakakni"/>
  
    </div>
  )
}
